Repository wecode-bootcamp-korea/26-1st-WETCHAPEDIA-frontend, pull requests merged in 2021-11, with the labels that each got.

#6 [26기 정지후] Add: NavFooter branch 생성
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/footerData.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/detailFeedNav.scss
  src/components/Nav/navData.js
  src/pages/Feeds/Feeds.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#11 [26기 최병현]Modify: 피드백 관련 수정
  src/config.js
  src/pages/Feeds/FeedLayout/SoleFeedLayout.js
  src/pages/Feeds/Feeds.js
  src/pages/Feeds/MovieList.js
Labels: Status: 리뷰 요청

#8 [26기 안재우]add: LoginRegister branch 생성
  src/components/Auth/Login/Login.js
  src/components/Auth/Login/Login.scss
  src/components/Auth/Login/LoginRegisterComponent/LoginRegister.js
  src/components/Auth/Login/LoginRegisterComponent/LoginRegister.scss
  src/components/Auth/Login/LoginRegisterComponent/button.js
  src/components/Auth/Login/LoginRegisterComponent/button.scss
  src/components/Auth/Login/LoginRegisterComponent/input.js
  src/components/Auth/Login/LoginRegisterComponent/input.scss
  src/components/Auth/Register/Register.js
  src/components/Auth/Register/Register.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/navData.js
Labels: Status: Conflict 해결 요청

#5 [26기 전창민] 상세페이지 기능구현 서버와 연결
  public/data/backendData.json
  public/data/movieData.json
  public/images/adimage.png
  public/images/background2.jpeg
  public/images/blackstar.png
  public/images/bookmark.jpeg
  public/images/dotmenu.png
  public/images/emptystar.png
  public/images/facebook.png
  public/images/looking.png
  public/images/moviebackground.jpeg
  public/images/movieposter.jpeg
  public/images/netflix.png
  public/images/pencil.png
  public/images/plus.png
  public/images/profile.jpeg
  public/images/star 2.jpeg
  public/images/star.jpeg
  public/images/starhalf 2.png
  public/images/starhalf.png
  public/images/thumb 2.png
  public/images/thumb.png
  public/images/tving 2.png
  public/images/tving.png
  public/images/userpicture 2.png
  public/images/userpicture.png
  public/images/wave 2.png
  public/images/wave.png
  src/Routes.js
  src/components/Auth/Login/LoginRegisterComponent/LoginRegister.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/DetailFeed/CommentIndividual/CommentIndividual.js
  src/pages/DetailFeed/CommentIndividual/CommentIndividuals.scss
  src/pages/DetailFeed/DetailFeed.js
  src/pages/DetailFeed/MovieCommentModal/MovieCommentModal.js
  src/pages/DetailFeed/MovieCommentModal/MovieCommentModal.scss
  src/pages/DetailFeed/MovieHeader/MovieHeader.js
  src/pages/DetailFeed/MovieHeader/MovieHeader.scss
  src/pages/DetailFeed/MovieInfos/MovieInfos.js
  src/pages/DetailFeed/MovieInfos/MovieInfos.scss
  src/pages/DetailFeed/MovieInfos/SlideCarousel.js
  src/pages/DetailFeed/MovieInfos/SlideCarousel.scss
  src/pages/DetailFeed/Profile/Profile.js
  src/pages/DetailFeed/Profile/Profile.scss
  src/pages/DetailFeed/SideElement/SideElement.js
  src/pages/DetailFeed/SideElement/SideElement.scss
  src/pages/DetailFeed/Star.js
  src/pages/DetailFeed/star.svg
  src/pages/Feeds/FeedLayout/SoleFeedLayout.js
  src/pages/Feeds/Feeds.js
  src/pages/Search/SearchFile.js
  src/styles/variables.scss
Labels: Status: 리뷰 요청
